services:
  tn5q8x2m4v:
    container_name: tn5q8x2m4v_app
    image: ghcr.io/mr-devloper005/treasurenftcode.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3076:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
